export const aptDetailsData = [
    {
      "APTName": "APT29",
      "APTRank": 1,
      "APTDescription": "APT29, also known as Cozy Bear, is a Russian cyber espionage group.",
      "targetsectors": [5, 7, 12, 21],
      "targetcountryids": [44, 102, 11],
      "attackids": ["T1071.001", "T1059.003"],
      "relatedCVEs": ["CVE-2018-4878", "CVE-2020-0601"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svg",
      "otherKnownNames": ["Cozy Bear", "The Dukes"],
      "APTID": "APT0001"
    },
    {
      "APTName": "APT28",
      "APTRank": 2,
      "APTDescription": "APT28, or Fancy Bear, is a Russian cyber espionage group.",
      "targetsectors": [3, 9, 11],
      "targetcountryids": [131, 22, 78],
      "attackids": ["T1071.003", "T1059.001"],
      "relatedCVEs": ["CVE-2017-11774", "CVE-2018-8653"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt28.jpg",
      "otherKnownNames": ["Fancy Bear", "Sofacy"],
      "APTID": "APT0002"
    },
    {
      "APTName": "APT41",
      "APTRank": 3,
      "APTDescription": "APT41 is a Chinese cyber espionage group known for both cyber espionage and financially motivated attacks.",
      "targetsectors": [10, 14, 23, 45],
      "targetcountryids": [57, 19, 89, 99],
      "attackids": ["T1071.001", "T1080"],
      "relatedCVEs": ["CVE-2019-3396", "CVE-2020-3118"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt41.jpg",
      "otherKnownNames": ["Barium", "Winnti"],
      "APTID": "APT0003"
    },
    {
      "APTName": "APT1",
      "APTRank": 4,
      "APTDescription": "APT1 is a Chinese cyber espionage group that has stolen hundreds of terabytes of data from at least 141 organizations.",
      "targetsectors": [2, 4, 25, 28],
      "targetcountryids": [56, 77, 88, 111],
      "attackids": ["T1105", "T1071.001"],
      "relatedCVEs": ["CVE-2017-0199", "CVE-2018-7600"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt1.jpg",
      "otherKnownNames": ["Comment Crew", "Shanghai Group"],
      "APTID": "APT0004"
    },
    {
      "APTName": "APT10",
      "APTRank": 5,
      "APTDescription": "APT10, also known as Stone Panda, is a Chinese cyber espionage group known for its campaign against managed IT service providers.",
      "targetsectors": [13, 20, 41],
      "targetcountryids": [101, 43, 76],
      "attackids": ["T1071.001", "T1106"],
      "relatedCVEs": ["CVE-2019-11510", "CVE-2019-0708"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt10.jpg",
      "otherKnownNames": ["Stone Panda", "Red Apollo"],
      "APTID": "APT0005"
    },
    {
      "APTName": "APT33",
      "APTRank": 6,
      "APTDescription": "APT33 is an Iranian cyber espionage group known for targeting aviation and energy sectors.",
      "targetsectors": [15, 33, 48],
      "targetcountryids": [9, 32, 27],
      "attackids": ["T1082", "T1071.001"],
      "relatedCVEs": ["CVE-2018-7602", "CVE-2018-8174"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt33.jpg",
      "otherKnownNames": ["Elfin", "Refined Kitten"],
      "APTID": "APT0006"
    },
    {
      "APTName": "APT32",
      "APTRank": 7,
      "APTDescription": "APT32, also known as OceanLotus, is a Vietnamese cyber espionage group.",
      "targetsectors": [5, 16, 37],
      "targetcountryids": [81, 57, 132],
      "attackids": ["T1069.001", "T1071.001"],
      "relatedCVEs": ["CVE-2017-8759", "CVE-2018-8174"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt32.jpg",
      "otherKnownNames": ["OceanLotus", "SeaLotus"],
      "APTID": "APT0007"
    },
    {
      "APTName": "APT3",
      "APTRank": 8,
      "APTDescription": "APT3 is a Chinese cyber espionage group known for targeting a variety of industries.",
      "targetsectors": [6, 18, 34],
      "targetcountryids": [61, 44, 90],
      "attackids": ["T1105", "T1071.001"],
      "relatedCVEs": ["CVE-2017-0199", "CVE-2018-4878"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt3.jpg",
      "otherKnownNames": ["Buckeye", "Gothic Panda"],
      "APTID": "APT0008"
    },
    {
      "APTName": "APT12",
      "APTRank": 9,
      "APTDescription": "APT12 is a Chinese cyber espionage group known for targeting Japanese and Taiwanese organizations.",
      "targetsectors": [7, 22, 49],
      "targetcountryids": [22, 65, 88],
      "attackids": ["T1071.001", "T1059.003"],
      "relatedCVEs": ["CVE-2017-0143", "CVE-2019-0708"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt12.jpg",
      "otherKnownNames": ["IXESHE", "Numbered Panda"],
      "APTID": "APT0009"
    },
    {
      "APTName": "APT37",
      "APTRank": 10,
      "APTDescription": "APT37, or Reaper, is a North Korean cyber espionage group that focuses on South Korean entities.",
      "targetsectors": [8, 17, 52],
      "targetcountryids": [34, 79, 91],
      "attackids": ["T1080", "T1071.001"],
      "relatedCVEs": ["CVE-2018-4878", "CVE-2019-0708"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt37.jpg",
      "otherKnownNames": ["Reaper", "ScarCruft"],
      "APTID": "APT0010"
    },
    {
      "APTName": "APT38",
      "APTRank": 11,
      "APTDescription": "APT38 is a North Korean cybercrime group responsible for several high-profile financial heists.",
      "targetsectors": [11, 14, 50],
      "targetcountryids": [102, 77, 59],
      "attackids": ["T1071.003", "T1090"],
      "relatedCVEs": ["CVE-2017-11774", "CVE-2019-11510"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt38.jpg",
      "otherKnownNames": ["Lazarus Group", "BlueNoroff"],
      "APTID": "APT0011"
    },
    {
      "APTName": "APT39",
      "APTRank": 12,
      "APTDescription": "APT39 is an Iranian cyber espionage group primarily targeting the telecommunications sector.",
      "targetsectors": [3, 13, 38],
      "targetcountryids": [100, 23, 58],
      "attackids": ["T1106", "T1071.001"],
      "relatedCVEs": ["CVE-2019-0708", "CVE-2018-7602"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt39.jpg",
      "otherKnownNames": ["Chafer", "Remix Kitten"],
      "APTID": "APT0012"
    },
    {
      "APTName": "APT5",
      "APTRank": 13,
      "APTDescription": "APT5 is a Chinese cyber espionage group known for targeting high-tech and defense industries.",
      "targetsectors": [10, 19, 27],
      "targetcountryids": [12, 31, 54],
      "attackids": ["T1105", "T1071.001"],
      "relatedCVEs": ["CVE-2017-0143", "CVE-2018-4878"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt5.jpg",
      "otherKnownNames": ["Manganese", "NUCLEON"],
      "APTID": "APT0013"
    },
    {
      "APTName": "APT6",
      "APTRank": 14,
      "APTDescription": "APT6 is an advanced Chinese cyber espionage group known for its prolonged campaigns.",
      "targetsectors": [9, 24, 53],
      "targetcountryids": [15, 45, 60],
      "attackids": ["T1071.001", "T1080"],
      "relatedCVEs": ["CVE-2019-0708", "CVE-2018-7602"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt6.jpg",
      "otherKnownNames": ["Jade Panda", "White Feather"],
      "APTID": "APT0014"
    },
    {
      "APTName": "APT7",
      "APTRank": 15,
      "APTDescription": "APT7 is a cyber espionage group targeting multiple sectors worldwide.",
      "targetsectors": [12, 29, 42],
      "targetcountryids": [39, 64, 81],
      "attackids": ["T1071.003", "T1059.001"],
      "relatedCVEs": ["CVE-2017-8759", "CVE-2019-11510"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt7.jpg",
      "otherKnownNames": ["Scarlet Spider", "Red Tornado"],
      "APTID": "APT0015"
    },
    {
      "APTName": "APT8",
      "APTRank": 16,
      "APTDescription": "APT8 is a cyber espionage group known for targeting financial institutions.",
      "targetsectors": [11, 15, 26],
      "targetcountryids": [28, 52, 99],
      "attackids": ["T1080", "T1071.001"],
      "relatedCVEs": ["CVE-2018-4878", "CVE-2017-8759"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt8.jpg",
      "otherKnownNames": ["Cobalt Group", "LuminousMoth"],
      "APTID": "APT0016"
    },
    {
      "APTName": "APT9",
      "APTRank": 17,
      "APTDescription": "APT9 is a cyber espionage group with a focus on government and defense sectors.",
      "targetsectors": [4, 18, 47],
      "targetcountryids": [26, 53, 92],
      "attackids": ["T1106", "T1071.001"],
      "relatedCVEs": ["CVE-2019-0708", "CVE-2018-4878"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt9.jpg",
      "otherKnownNames": ["Aurora Panda", "Dragonfly"],
      "APTID": "APT0017"
    },
    {
      "APTName": "APT11",
      "APTRank": 18,
      "APTDescription": "APT11 is a Chinese cyber espionage group targeting high-value technology organizations.",
      "targetsectors": [6, 21, 35],
      "targetcountryids": [30, 48, 74],
      "attackids": ["T1071.001", "T1059.003"],
      "relatedCVEs": ["CVE-2017-0143", "CVE-2018-8174"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt11.jpg",
      "otherKnownNames": ["Steel Eagle", "Bronze Butler"],
      "APTID": "APT0018"
    },
    {
      "APTName": "APT13",
      "APTRank": 19,
      "APTDescription": "APT13 is a Chinese cyber espionage group with a focus on Western organizations.",
      "targetsectors": [1, 31, 43],
      "targetcountryids": [33, 66, 82],
      "attackids": ["T1071.001", "T1080"],
      "relatedCVEs": ["CVE-2018-7602", "CVE-2019-11510"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt13.jpg",
      "otherKnownNames": ["Red Lotus", "BlackCloud"],
      "APTID": "APT0019"
    },
    {
      "APTName": "APT14",
      "APTRank": 20,
      "APTDescription": "APT14 is a Chinese cyber espionage group known for targeting government organizations.",
      "targetsectors": [14, 25, 46],
      "targetcountryids": [14, 41, 76],
      "attackids": ["T1071.003", "T1059.001"],
      "relatedCVEs": ["CVE-2018-4878", "CVE-2019-0708"],
      "imgurl": "https://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svghttps://socradar.io/labs/static/img/icon/threat_actor/search_card_image.svgapt14.jpg",
      "otherKnownNames": ["Silent Lotus", "Ghost Dragon"],
      "APTID": "APT0020"
    }
  ]
  